---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ns4
    groups:
      - dns
    hostname: ns4
    docker_networks:
      - name: bind
        ipam_config:
          - subnet: "10.11.0.0/16"
            gateway: "10.11.0.254"
    networks:
      - name: bind
        ipv4_address: "10.11.0.4"
    image: "geerlingguy/docker-${MOLECULE_DISTRO}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${PWD}:/etc/ansible/roles/bertvv.bind:ro
      - ${PWD}/library:/root/.ansible/plugins/modules:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: ns5
    hostname: ns5
    groups:
      - dns
    networks:
      - name: bind
        ipv4_address: "10.11.0.5"
    image: "geerlingguy/docker-${MOLECULE_DISTRO}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${PWD}:/etc/ansible/roles/bertvv.bind:ro
      - ${PWD}/library:/root/.ansible/plugins/modules:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_legacy_silent
      deprecation_warnings: false
      remote_tmp: /tmp
    ssh_connection:
      pipelining: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
